cssnano/cssnano

README.md
https://github.com/sindresorhus/grunt-cssnano
=> add `grunt-cssnano` to readme

README.md
https://github.com/sindresorhus/broccoli-cssnano
=> add `broccoli-cssnano` to the readme

index.js
closes #9 
dammit, continue to fails... and this tape + tap-spec :laughing:
can you investigate why? there's no logic for that when all other tests work.
i think it isn't from `postcss-conver-values` as you mentioned, cuz i review its new commits.
=> refactor index, closes #9

.gitignore, index.js, package.json, tests/webpack.js
=> Make cssnano compatible with browserify/webpack

CHANGELOG.md, metadata.json, package.json, src/__tests__/modules/postcss-discard-overridden.js, src/index.js
=> Added: Remove overridden at-rules.

CHANGELOG.md, metadata.json, src/__tests__/modules/cssnano-reduce-timing-functions.js, src/index.js, src/lib/reduceTimingFunctions.js
Further reading: https://drafts.csswg.org/css-transitions/#transition-timing-function-property
=> Added: Reduce transition timing functions.

metadata.json
=> Fixed mergeldents documentation error

metadata.toml, src/__tests__/modules/cssnano-reduce-background-repeat.js, src/__tests__/modules/cssnano-reduce-display-values.js, src/__tests__/util/getData.js, src/index.js, src/lib/evenValues.js, src/lib/reduceBackgroundRepeat.js, src/lib/reduceDisplayValues.js, src/lib/reduceTimingFunctions.js
https://drafts.csswg.org/css-display/#the-display-properties
=> Reduce display shorthands

metadata.toml
=> Add mising comma

packages/cssnano/src/index.js
Fixes #375. I'm not sure how to create a unit test for this, however I have tested it manually.
=> Fix loading of configuration files

packages/postcss-minify-gradients/package.json, packages/postcss-minify-gradients/src/__tests__/index.js, packages/postcss-minify-gradients/src/index.js
ref: https://webkit.org/blog/1424/css3-gradients/
=> fix: postcss-minify-gradients to support old syntax, Close #386

packages/stylehacks/src/__tests__/mediaSlash0Slash9.js, packages/stylehacks/src/__tests__/slash9.js, packages/stylehacks/src/plugins/index.js, packages/stylehacks/src/plugins/mediaSlash0Slash9.js
Example:
```css
@media \0screen\,screen\9 {}
```
=> Feature(stylehacks): add new hack.

packages/stylehacks/src/__tests__/_processCSS.js, packages/stylehacks/src/__tests__/leadingUnderscore.js, packages/stylehacks/src/plugins/leadingUnderscore.js
Ref: https://github.com/ben-eb/cssnano/issues/395
=> Fixed(stylehacks): prefixed value now ignored.

packages/postcss-merge-longhand/src/__tests__/borders.js
fixes #450
Looks it is already fixed, just add tests.
=> tests: merge longhand using custom variables

packages/postcss-minify-font-values/src/__tests__/index.js, packages/postcss-minify-font-values/src/lib/minify-family.js, packages/postcss-minify-font-values/src/lib/minify-weight.js, packages/postcss-minify-font-values/src/lib/uniqs.js
fixes #430 fixes #434
Also fix buggy tests. Can add more tests.
=> fix: improve `font-family` handling

packages/postcss-colormin/src/__tests__/index.js, packages/postcss-colormin/src/index.js
=> fix: add extra space after hex color and function

packages/postcss-normalize-url/src/__tests__/index.js, packages/postcss-normalize-url/src/index.js
=> fix: better handle url with `data` and `extension`

packages/postcss-convert-values/src/__tests__/index.js, packages/postcss-convert-values/src/index.js
=> fix: handle uppercase in convert values

packages/postcss-normalize-url/src/__tests__/index.js, packages/postcss-normalize-url/src/index.js
=> fix: skip convert empty urls

packages/postcss-merge-longhand/src/__tests__/borders.js
=> tests: merge `border` and `border-width` (`border-*-width`)

packages/postcss-ordered-values/src/__tests__/index.js, packages/postcss-ordered-values/src/rules/border.js
=> fix: invalid border property stay invalid (#484)

packages/postcss-merge-longhand/src/__tests__/borders.js, packages/postcss-merge-longhand/src/__tests__/columns.js
[fixed](https://github.com/cssnano/cssnano/pull/486#issuecomment-397662715)
=> Fixes of pull #486

package.json, packages/postcss-normalize-unicode/src/__tests__/index.js, packages/postcss-normalize-unicode/src/index.js
Sorry, closed the previous PR by mistake. 
fixes #524
=> fix: postcss-normalize-unicode causes bugs in IE11

package.json, packages/postcss-colormin/package.json, packages/postcss-colormin/yarn.lock, packages/postcss-merge-rules/package.json, packages/postcss-merge-rules/yarn.lock, packages/postcss-minify-params/package.json, packages/postcss-minify-params/yarn.lock, packages/postcss-reduce-initial/package.json, packages/postcss-reduce-initial/yarn.lock, packages/stylehacks/package.json, packages/stylehacks/yarn.lock, yarn.lock
=> feat: update `browserslist` to latest version

packages/postcss-minify-font-values/src/__tests__/index.js
=> test: font-family with multiple \

site/content/changelog.md
monorepo require a lot of actions, i think we should automate some action using `npm` scripts
=> docs(site): update

packages/cssnano-preset-advanced/src/__tests__/integrations/basscss5.css, packages/cssnano-preset-advanced/src/__tests__/integrations/bulma.css, packages/cssnano-preset-default/src/__tests__/integrations/basscss5.css, packages/cssnano-preset-default/src/__tests__/integrations/bulma.css, packages/postcss-merge-longhand/package.json, packages/postcss-merge-longhand/src/__tests__/borders.js, packages/postcss-merge-longhand/src/lib/canExplode.js, packages/postcss-merge-longhand/src/lib/canMerge.js, packages/postcss-merge-longhand/src/lib/decl/borders.js, packages/postcss-merge-longhand/src/lib/decl/boxBase.js, packages/postcss-merge-longhand/src/lib/decl/columns.js, packages/postcss-merge-longhand/src/lib/minifyWsc.js, packages/postcss-merge-longhand/src/lib/parseWsc.js, packages/postcss-merge-longhand/src/lib/validateWsc.js
Added more precise parsing of `width` `style` `color`, which in turn has opened the door to parse borders with custom properties. Also added an additional border optimisation, increasing compression.
=> Refactor postcss-merge-longhand

packages/postcss-merge-longhand/src/__tests__/borders.js, packages/postcss-merge-longhand/src/lib/minifyWsc.js
=> fix(postcss-merge-longhand): border minification throwing error

packages/cssnano-preset-advanced/src/__tests__/integrations/schema.css, packages/cssnano-preset-advanced/src/__tests__/integrations/semantic2.css, packages/cssnano-preset-default/src/__tests__/integrations/schema.css, packages/cssnano-preset-default/src/__tests__/integrations/semantic2.css, packages/postcss-merge-longhand/src/__tests__/borders.js, packages/postcss-merge-longhand/src/lib/decl/borders.js, packages/postcss-merge-longhand/src/lib/minifyWsc.js, packages/postcss-merge-longhand/src/lib/parseWsc.js
Fixes #579. 
The changes should also lead to slightly better compression (e.g. [1](https://github.com/cssnano/cssnano/pull/583/files#diff-b6189c20f0edb0a28d43eb41e7e241f1L3199)).
=> fix(postcss-merge-longhand): Should not mangle borders (#579)

packages/postcss-normalize-timing-functions/src/index.js
out of scope this plugin, it should be done other plugin what we implement in future
=> fix: do not lowercased property

packages/cssnano-preset-advanced/yarn.lock, packages/cssnano-preset-default/yarn.lock, packages/cssnano/src/__tests__/issue579.js, packages/cssnano/yarn.lock
fixes #578
Fixed in original package. Just update your lock files.
=> fix: parse error with iPhone X feature

packages/postcss-normalize-positions/README.md, packages/postcss-normalize-positions/src/__tests__/index.js, packages/postcss-normalize-positions/src/index.js
=> fix: handle uppercase property and values on `postcss-normalize-positons`

packages/cssnano/src/__tests__/presets.js, packages/cssnano/src/index.js
=> Fix toggling of plugins in presets

packages/postcss-merge-longhand/src/__tests__/borders.js, packages/postcss-merge-longhand/src/lib/decl/borders.js
=> Fix bug in merging border properties with custom properties

packages/cssnano/src/index.js
fixes #651
I find a lot of problems with perf, i will try to fix it tomorrow
=> fix: load time

packages/postcss-merge-rules/src/lib/ensureCompatibility.js
=> perf(postcss-merge-rules): increase perf

packages/postcss-colormin/src/colours.js, packages/postcss-colormin/src/index.js, packages/postcss-colormin/src/lib/toShorthand.js
=> perf(postcss-colormin): increase

packages/cssnano-util-same-parent/src/__tests__/index.js, packages/cssnano-util-same-parent/src/index.js, packages/postcss-merge-idents/src/__tests__/index.js, packages/postcss-merge-idents/src/index.js, packages/postcss-merge-rules/src/__tests__/index.js
=> fix(merge-rules, merge-idents): add support for nested at-rules

packages/postcss-minify-gradients/src/__tests__/index.js, packages/postcss-minify-gradients/src/index.js
=> fix(postcss-minify-gradients): don't break gradients with `var` and `env` functions

packages/postcss-svgo/package.json
=> fix(postcss-svgo): security problem with `js-yaml`

packages/postcss-minify-font-values/src/__tests__/index.js, packages/postcss-minify-font-values/src/index.js, packages/postcss-minify-font-values/src/lib/minify-font.js
=> fix(postcss-minify-font-values): correct minify font family with css variables

packages/postcss-reduce-transforms/src/__tests__/index.js
close #834
Added test to ensure `rotate3d` works
=> test: to close #834

azure-pipelines.yml
Follow up of https://github.com/cssnano/cssnano/pull/840
=> chore: dropped node v6 and v8

packages/css-size/package.json, packages/css-size/src/index.js, packages/css-size/yarn.lock
[cli-table](npmjs.com/package/cli-table) is not maintained anymore, upgrade to [cli-table3](npmjs.com/package/cli-table3)
=> chore(deps): upgrade to cli-table3

packages/postcss-ordered-values/src/__tests__/index.js, packages/postcss-ordered-values/src/index.js
Refer #756 
added support for 
Added tests for the same
=> chore(ordered-values): added support for more border props

packages/postcss-ordered-values/src/rules/flexFlow.js
=> refactor: prettify

packages/cssnano/package.json, packages/cssnano/yarn.lock
=> chore: show up collective information after installation

README.md
=> chore: added opencollective in the readme.md

packages/postcss-merge-rules/src/__tests__/index.js, packages/postcss-merge-rules/src/lib/ensureCompatibility.js
closes https://github.com/cssnano/cssnano/pull/781
fixes https://github.com/cssnano/cssnano/issues/642
=> chore: fixed focus-visible issue and added tests

packages/postcss-convert-values/src/__tests__/index.js, packages/postcss-convert-values/src/index.js
=> fix: Keep math functions together

.github/ISSUE_TEMPLATE/feature_request.md
=> chore: update issue template

packages/cssnano/package.json, packages/cssnano/src/index.js, packages/cssnano/yarn.lock
Ref https://github.com/davidtheclark/cosmiconfig/blob/master/CHANGELOG.md#600
The new version slightly changed api, dropped old node support and
tweaked dependencies.
=> Upgrade cosmiconfig

README.md
=> Fixed bad links to documentation in README

CONTRIBUTING.md
As discussed in https://github.com/cssnano/cssnano/pull/998
=> docs: add release instructions

packages/postcss-convert-values/src/__tests__/index.js, packages/postcss-merge-longhand/src/__tests__/borders.js
Add tests from https://github.com/cssnano/cssnano/pull/941 and https://github.com/cssnano/cssnano/pull/956 to prevent regressions.
=> Add tests for fixed edge cases

site/package.json, site/yarn.lock
* update Docusarus to beta.0
* regenerate yarn.lock to fix vulnerability reports
Should close https://github.com/cssnano/cssnano/pull/1069 and close https://github.com/cssnano/cssnano/pull/1041.
=> chore(site): update all website dependencies

site/package.json, site/yarn.lock
Update docusaurus to latest release.
Seem mostly layout fixes https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.1
=> chore(docs): update docusaurus

site/package.json, site/yarn.lock
I also regenerate `yarn.lock` so a few duplicates (csswhat, cssselect, jest-worker) go away.
=> chore(docs): update to latest docusaurus

packages/postcss-ordered-values/script/buildListStyleType.js
=> chore: fix GitHub format

packages/postcss-colormin/src/__tests__/index.js
=> test(postcss-colormin): ignore variables with same name as color

package.json, packages/cssnano-utils/src/__tests__/getArguments.test.js, packages/cssnano-utils/src/getArguments.js, packages/postcss-colormin/package.json, packages/postcss-convert-values/package.json, packages/postcss-merge-idents/package.json, packages/postcss-merge-longhand/package.json, packages/postcss-minify-font-values/package.json, packages/postcss-minify-gradients/package.json, packages/postcss-minify-params/package.json, packages/postcss-normalize-display-values/package.json, packages/postcss-normalize-positions/package.json, packages/postcss-normalize-repeat-style/package.json, packages/postcss-normalize-string/package.json, packages/postcss-normalize-timing-functions/package.json, packages/postcss-normalize-unicode/package.json, packages/postcss-normalize-url/package.json, packages/postcss-normalize-whitespace/package.json, packages/postcss-ordered-values/package.json, packages/postcss-reduce-idents/package.json, packages/postcss-reduce-transforms/package.json, packages/postcss-svgo/package.json, yarn.lock
* Change test to match new AST
* Avoid creating anonymous function
=> chore: update postcss-value-parser

packages/css-size/src/__tests__/index.js, packages/cssnano/package.json, packages/postcss-merge-rules/package.json
Add missing devDependencies or tests will fail with stricter package managers.
=> test: declare all test dependencies in devDependencies

packages/cssnano/CHANGELOG.md, packages/cssnano/package.json, site/docs/changelog.md, site/docusaurus.config.js
Next, I would like to work on adding TypeScript type declarations so we can solve https://github.com/cssnano/cssnano/pull/1254#discussion_r759637797
=> Publish cssnano 5.0.14

site/docs/config-file.mdx, site/package.json, site/pnpm-lock.yaml
Also add `@mdx/react` as a direct dependency, else the site does not build with pnpm (see https://github.com/facebook/docusaurus/issues/5803)
=> docs: improve preset documentation

package.json, pnpm-lock.yaml
uvu fixed an annoying bug with ignoring files: https://github.com/lukeed/uvu/issues/111
=> chore: update uvu and other dev deps

packages/postcss-colormin/src/index.js, packages/postcss-merge-longhand/src/lib/canExplode.js, packages/postcss-minify-gradients/src/isColorStop.js, packages/postcss-minify-selectors/src/index.js, packages/postcss-normalize-positions/src/index.js, packages/postcss-normalize-repeat-style/src/index.js, packages/postcss-normalize-whitespace/src/index.js, packages/postcss-ordered-values/src/lib/mathfunctions.js, packages/postcss-ordered-values/src/rules/border.js, packages/postcss-ordered-values/src/rules/boxShadow.js, packages/postcss-ordered-values/src/rules/flexFlow.js, packages/postcss-ordered-values/src/rules/listStyle.js
=> refactor: replace array with set if used as set

packages/postcss-discard-unused/src/index.js
Set can replace this function as elsehwere in the codebase.
=> refactor(postcss-discard-unused): remove uniqs function

packages/postcss-ordered-values/src/index.js, packages/postcss-ordered-values/src/rules/animation.js
- don't re-create the same list on every function call
- replace object with map
=> refactor(postcss-ordered-values): improve data structures

package.json, pnpm-lock.yaml
eslint must come last otherwise the --fix flag has no effect
=> chore: fix fixlint command

packages/cssnano/src/index.js, packages/postcss-colormin/src/index.js, packages/postcss-convert-values/src/index.js, packages/postcss-discard-unused/src/index.js, packages/postcss-merge-longhand/src/lib/decl/borders.js, packages/postcss-merge-longhand/src/lib/getDecls.js, packages/postcss-merge-longhand/src/lib/mergeRules.js, packages/postcss-merge-longhand/src/lib/validateWsc.js, packages/postcss-merge-rules/src/lib/ensureCompatibility.js, packages/postcss-minify-selectors/src/index.js, packages/postcss-normalize-positions/src/index.js
* missing undefined or null checks
* missing checks on the appropriate node type
* functions that return a mix of boolean and falsy values
I think it might be easier to review if I separate the changes that affect the running code from comments and generated types.
=> chore: fix various issues that TypeScript found

package.json, pnpm-lock.yaml
Update TypeScript to the final 4.6 release.
=> chore: update TypeScript and ESLint

.github/workflows/test.yml
Update GitHub actions to latest version and update pnpm
=> chore: update GitHub actions

package.json, pnpm-lock.yaml, site/.eslintrc.json
We don't need it as the website does not use React any more
=> chore: remove eslint React plugin

packages/cssnano-preset-advanced/CHANGELOG.md, packages/cssnano-preset-advanced/package.json, packages/cssnano-preset-default/CHANGELOG.md, packages/cssnano-preset-default/package.json, packages/cssnano/CHANGELOG.md, packages/cssnano/package.json, packages/postcss-discard-comments/CHANGELOG.md, packages/postcss-discard-comments/package.json, packages/postcss-unique-selectors/CHANGELOG.md, packages/postcss-unique-selectors/package.json, pnpm-lock.yaml
Fix comment removal when running PostCSS > 8.4.6
=> Publish cssnano 5.1.1

site/.eleventy.js, site/package.json, site/pnpm-lock.yaml, site/src/_includes/footer.njk
* retrieve release number from cssnano package
* update dependencies
=> docs update site

packages/cssnano-preset-advanced/CHANGELOG.md, packages/cssnano-preset-advanced/package.json, packages/cssnano-preset-default/CHANGELOG.md, packages/cssnano-preset-default/package.json, packages/cssnano/CHANGELOG.md, packages/cssnano/package.json, packages/postcss-merge-longhand/CHANGELOG.md, packages/postcss-merge-longhand/package.json, pnpm-lock.yaml
=> Publish cssnano 5.1.4

packages/cssnano-preset-advanced/CHANGELOG.md, packages/cssnano-preset-advanced/package.json, packages/postcss-reduce-idents/CHANGELOG.md, packages/postcss-reduce-idents/package.json
Release the changes in https://github.com/cssnano/cssnano/pull/1366
=> Publish cssnano-preset-advanced and postcss-reduce-idents

packages/postcss-minify-params/src/index.js
Replace function bind with arrrow function as it is easier to understand
at first glance.
=> refactor(postcss-minify-params): replace function bind

site/package.json, site/pnpm-lock.yaml, site/src/playground-editor.js, site/src/playground.njk
- Update Codemirror to 0.20
- Update build dependencies
=> docs: update website dependencies

packages/postcss-ordered-values/src/index.js, packages/postcss-ordered-values/test/index.js
=> fix(postcss-ordered-values): preserve constant values

site/.eleventy.js, site/package.json, site/pnpm-lock.yaml, site/src/docs/getting-started.md, site/src/docs/what-are-optimisations.md, site/src/playground.js, site/src/playground.njk
Updated the website dependencies and fixed a few accessibility issues that the Axe browser extension found.
=> docs: update website and improve accessibility

packages/cssnano-preset-default/package.json, pnpm-lock.yaml
=> fix(cssnano-preset-default): update css-declaration-sorter

site/package.json, site/pnpm-lock.yaml, site/src/docs/introduction.md, site/src/playground.njk, site/src/styles/index.css
Dependency updates and a few appearance tweaks.
=> docs: update website for release

.changeset/honest-ravens-serve.md, packages/cssnano/package.json, packages/cssnano/src/index.js, pnpm-lock.yaml
=> feat!(cssnano): remove YAML config support

packages/cssnano-preset-default/package.json, pnpm-lock.yaml
=> fix(cssnano-preset-default): update postcss-calc

site/src/index.njk
due to the changes out of cssnano@b2ca6bb the URL of this page has changed.
=> fix(docs): URL

.changeset/short-falcons-help.md, packages/cssnano/package.json, pnpm-lock.yaml
set lilconfig minimum version to one without vulnerabilities see https://github.com/antonk52/lilconfig/releases/tag/v3.1.1
=> fix(cssnano): update minimum lilconfig version

site/.eleventy.js, site/package.json, site/pnpm-lock.yaml, site/src/CNAME, site/src/_includes/footer.njk, site/src/docs/community.md, site/src/playground.njk
Close https://github.com/cssnano/cssnano/issues/1569
=> docs: update website

.changeset/fresh-wolves-design.md, packages/postcss-minify-font-values/README.md, packages/postcss-minify-font-values/src/index.js, packages/postcss-minify-font-values/test/index.js
`removeQuotes` supports custom functions to handle CSS variables.
=> feat: `removeQuotes` support custom functions

packages/cssnano/test/issue1527.js, packages/postcss-convert-values/src/index.js, packages/postcss-convert-values/test/index.js
=> fix(postcss-convert-values): convert `0ms` to `0s`

.github/workflows/test.yml
[nodejs/node@v24.0.0 (release)](https://github.com/nodejs/node/releases/tag/v24.0.0)
=> ci: use Node.js 24

site/package.json, site/pnpm-lock.yaml
=> chore: update eleventy
