README.md
Actually use stidin redirection instead of piping. Think of the kittens!
=> Correct the stdio redirection example

index.js, lib/styleCache.js, package.json, tests/issue26.css, tests/issue26.expected.css, tests/issue26.js
This should fix any whitespace issues when combining cssnano with PostCSS plugins that utilise `node.clone()`. Would be nice to get some confirmation.
/cc @meuwka @faergeek @benfrain @ai
=> Add processor to reset styleCache. Fixes #26.

index.js, tests/api.js
Ref: https://github.com/ben-eb/cssnano/issues/84
I think it might be fine to re-assign the property internally, instead of changing the name.
=> Resolve a crash when using the safe option via wrapper plugin.

src/__tests__/integrations.js, src/__tests__/integrations/basscss5.css, src/__tests__/modules/cssnano-reduce-positions.js, src/index.js, src/lib/reducePositions.js
This transformation works for the longhand property `background-position` and also the `background` shorthand. Conversions are as follows:
| original        | result      |
|-----------------|-------------|
| `top center`    | `top`       |
| `center top`    | `top`       |
| `top right`     | `100% 0`    |
| `top left`      | `0 0`       |
| `right`         | `100%`      |
| `right center`  | `100%`      |
| `center right`  | `100%`      |
| `right top`     | `100% 0`    |
| `right bottom`  | `100% 100%` |
| `bottom center` | `bottom`    |
| `center bottom` | `bottom`    |
| `bottom right`  | `100% 100%` |
| `bottom left`   | `0 100%`    |
| `left`          | `0`         |
| `left center`   | `0`         |
| `center left`   | `0`         |
| `left top`      | `0 0`       |
| `left …
=> Add optimiser for background position values.

CHANGELOG.md, metadata.json, src/__tests__/modules/cssnano-reduce-positions.js, src/lib/reducePositions.js
Further reading:
* https://developer.mozilla.org/en-US/docs/Web/CSS/perspective-origin
* https://developer.mozilla.org/en-US/docs/Web/CSS/position_value
Something to note for the future - we can do this transform in the `transform-origin` property also, however the logic is a bit different. We'll need to refactor how the tests work in order to make sure it works properly. See https://developer.mozilla.org/en-US/docs/Web/CSS/transform-origin.
=> Add perspective-origin to the reduce-positions transform.

CHANGELOG.md, metadata.json, src/__tests__/modules/cssnano-reduce-background-repeat.js, src/index.js, src/lib/getArguments.js, src/lib/getMatch.js, src/lib/reduceBackgroundRepeat.js, src/lib/reducePositions.js, src/lib/reduceTimingFunctions.js
I need this to be tested on real-world CSS files to ensure that no breakages occur.
This is a simple transform to reduce `background-repeat` definitions both in the `background` shorthand property and the `background-repeat` property.
```css
.box {
background-repeat: repeat no-repeat;
}
```
```css
.box {
background-repeat: repeat-x;
}
```
This code builds on the functionality from the `reduce-positions` transform and so a lot of code looks fairly similar. It might be worthwhile to consolidate some of these transformation functions in future releases, but for now I think this is good as is.
I consider this to be a safe transform as it is converting the two value syntax to the single value syntax, *where possible*, as defined in the specification.
* MDN: …
=> Added: Reduce background-repeat definitions.

src/__tests__/api.js, src/index.js
When processing multiple files with safe flag set as true, the first time it will set the safe options as null due to PostCSS throwing an error if passed in. This then means the following files will not process with the safe flag as enabled. Instead it will now set isSafe as true on the options config for the next processed files to persist the the safe option.
Fix for issue: #268
=> fixed safe option not persisting for multiple files

src/lib/reduceDisplayValues.js
Seems to be a typo. The tests are based on the mappings in this file, so it was uncaught. This is per the CSS3 display module spec:
https://drafts.csswg.org/css-display/#the-display-properties
=> `inline list-item` -> `inline-list-item`

.travis.yml, package.json
Speed up CI by caching the development dependencies. The 1st run is uncached then the 2nd and 3rd are cached, timings are in seconds. A lot of fluctuations but overall except from the bold outlier it's an improvement.
Run | Node 4 | Node 5 | Node 6 | Node 7
----- | --------- | -------- | --------- | ----------
[1st](https://travis-ci.org/ben-eb/cssnano/builds/253924950) | 628 | 184 | 330 | 159
[2nd](https://travis-ci.org/ben-eb/cssnano/builds/253930585) | 196 | 139 | 142 | **266**
[3rd](https://travis-ci.org/ben-eb/cssnano/builds/253936063) | 367 | 126 | 279 | 118
=> Speed up CI builds by caching development dependencies

.travis.yml
As of npm@2.6.1, the npm update will only inspect top-level packages.
Prior versions of npm would also recursively inspect all dependencies.
The old recursive behaviour causes version mismatches.
See https://github.com/ben-eb/cssnano/pull/388#issuecomment-315902885 for more context.
=> Fix CI module caching for npm versions older than 2.6.1

packages/cssnano/src/index.js
`fromFile` was trying to access the `Root` nodes `source` property, which is not always set (for example when creating it with `postcss.root()`.
This just adds an additional check for `css.source` in `fromFile`.
=> Fix resolveConfig for Root without source

packages/postcss-merge-longhand/src/__tests__/borders.js, packages/postcss-merge-longhand/src/lib/decl/borders.js
Condenses redundant border-spacing values. This addresses #267
=> Feature: Convert doubled border-spacing values

packages/postcss-minify-params/package.json, packages/postcss-minify-params/src/__tests__/index.js, packages/postcss-minify-params/src/index.js, packages/postcss-minify-params/yarn.lock
fixes #432
IE 10 also have this bug, but 
```css
@media all and (min-width:500px){h1{color:blue}}
@media (min-width:500px){h1{color:blue}}
```
works fine in IE 10 and IE 11
=> fix: don't remove `all` for ie 10 and 11

packages/postcss-merge-rules/src/__tests__/index.js, packages/postcss-merge-rules/src/index.js
Fix https://github.com/ben-eb/cssnano/issues/458
=> Place all rules with "all" declaration on top

packages/postcss-merge-rules/src/__tests__/index.js, packages/postcss-merge-rules/src/index.js
=> fix(postcss-merge-rules): check for ms vendor

packages/cssnano/package.json, packages/cssnano/src/__tests__/issue420.js, packages/cssnano/yarn.lock
Test for checking integration with `postcss-font-magician` with `display` parameter.
fixes #420
=> Add test for checking issue #420

packages/postcss-merge-rules/package.json, packages/postcss-merge-rules/yarn.lock, packages/postcss-reduce-initial/package.json, packages/postcss-reduce-initial/yarn.lock
/cc @ai 
Should we use `ignoreUnkownVersions` in each `browserslist`?
=> chore(deps): update `caniuse-api` to `3.0.0` version

site/content/guides/getting-started.md
=> docs: remove `css-loader` from docs

site/src/layouts/Homepage/index.js
The website has the following notice on the homepage which no longer applies since v4 is released: 
>This documentation is for the upcoming version 4 release, which can be installed with npm install cssnano@next. Please test it out and report any bugs that you may find!
=> Remove v4 notice on homepage

packages/postcss-merge-longhand/src/__tests__/borders.js, packages/postcss-merge-longhand/src/lib/decl/borders.js, packages/postcss-merge-longhand/src/lib/getLastNode.js
=> fix(postcss-merge-longhand): Incorrect merging of border declarations

packages/cssnano-preset-advanced/src/__tests__/integrations/base.css, packages/cssnano-preset-advanced/src/__tests__/integrations/helium.css, packages/cssnano-preset-advanced/src/__tests__/integrations/picnic.css, packages/cssnano-preset-advanced/src/__tests__/integrations/schema.css, packages/cssnano-preset-advanced/src/__tests__/integrations/semantic2.css, packages/cssnano-preset-advanced/src/__tests__/integrations/turret.css, packages/cssnano-preset-advanced/src/__tests__/integrations/vital.css, packages/cssnano-preset-default/src/__tests__/integrations/base.css, packages/cssnano-preset-default/src/__tests__/integrations/helium.css, packages/cssnano-preset-default/src/__tests__/integrations/picnic.css, packages/cssnano-preset-default/src/__tests__/integrations/schema.css, packages/cssnano-preset-default/src/__tests__/integrations/semantic2.css, packages/cssnano-preset-default/src/__tests__/integrations/turret.css, packages/cssnano-preset-default/src/__tests__/integrations/vital.css, packages/postcss-merge-longhand/src/__tests__/borders.js, packages/postcss-merge-longhand/src/lib/decl/borders.js
Fixes #553 and #554. 
Incidentally, the fix also revealed some issues in the integration suite, as well as provided slightly better compression.
=> fix(postcss-merge-longhand): Should not mangle border output

packages/postcss-merge-longhand/src/__tests__/borders.js, packages/postcss-merge-longhand/src/lib/decl/borders.js
=> fix(postcss-merge-longhand): Should not convert currentColor

packages/postcss-merge-longhand/src/__tests__/borders.js, packages/postcss-merge-longhand/src/lib/decl/borders.js
=> fix(postcss-merge-longhand): Should not drop border-width with custom property from border shorthand

packages/postcss-merge-longhand/src/__tests__/borders.js, packages/postcss-merge-longhand/src/lib/decl/borders.js
=> fix(postcss-merge-longhand): Merge borders with custom properties correctly

packages/postcss-normalize-unicode/package.json, packages/postcss-normalize-unicode/yarn.lock
browserselist is imported [here](https://github.com/cssnano/cssnano/blob/master/packages/postcss-normalize-unicode/src/index.js#L1) but not in the package's dependency list
=> fix: postcss-normalize-unicode add browserslist to dependencies

packages/css-size/package.json
The package.json file for css-size has a reference for `"types"` to `css-size.d.ts`, but that file isn't in the published npm package. This adds the type definition to the list of published files for that package.
=> css-size: file was missing in css-size package.json.

package.json, util/testHelpers.js
While working on https://github.com/cssnano/cssnano/pull/580 I was struggling with the setup of this project. Made some small changes to hopefully make contributing a bit easier.
- running tests cause a lot of warnings in the console littering the test output, I first thought I did something wrong, setting `from` in the utils prevents this for most tests.
- got huge diffs from the frameworks, quickly found the `buildFrameworks` script but couldn't get it to run with `node`. After troubleshooting I found out `babel-node` should be used, putting it into a npm task/script clarifies this.
- I don't have `yarn` installed so wanting to install with `npm` I changed the client option in `lerna.json` however it still used `yarn`, removed this double option definition for easier switching.
=> Meta improvements

packages/postcss-merge-longhand/src/__tests__/borders.js, packages/postcss-merge-longhand/src/lib/decl/borders.js
Fixes #619. 
This change tries to switch out a custom property in a border shorthand declaration for a concrete value, moving the custom property to its own longhand representation.
=> fix(postcss-merge-longhand): Prefer concrete values over custom properties in shorthands

packages/postcss-merge-longhand/src/__tests__/borders.js, packages/postcss-merge-longhand/src/__tests__/boxBase.js, packages/postcss-merge-longhand/src/lib/canExplode.js, packages/postcss-merge-longhand/src/lib/canMerge.js
Increased the test coverage following the previous PR. I have done a small refactor to canMerge and canExplode to avoid duplication.
Not sure about the inclusion of 'none', I think it should be there but existing tests fail when I try to add it.
=> Refactor canMerge in postcss-merge-longhand

packages/postcss-merge-longhand/src/__tests__/borders.js, packages/postcss-merge-longhand/src/lib/decl/borders.js
=> fix(postcss-merge-longhand): Should not throw error when a border property value is undefined

packages/postcss-merge-longhand/src/__tests__/borders.js, packages/postcss-merge-longhand/src/__tests__/boxBase.js, packages/postcss-merge-longhand/src/__tests__/columns.js, packages/postcss-merge-longhand/src/lib/parseWsc.js
Fix matches var(--somename) and preserve case of the variable name.
Fixes #648
=> Preserve case of css custom variables. Fixes #648

packages/postcss-minify-params/src/__tests__/index.js, packages/postcss-minify-params/src/index.js
The `:first` pseudo-class is meant to be used with the `@page` at-rule to apply some style to the first page of a printed document (https://developer.mozilla.org/en-US/docs/Web/CSS/:first).
The `minifyParams` optimization causes it to be mangled :
it's transformed from
`@page :first { margin: 0 }`
to
`@page ,first { margin: 0 }`.
This commit fixes this behavior and closes cssnano/cssnano#677
=> fix: do not mangle `@page :first` rules (closes #677)

packages/postcss-minify-params/src/__tests__/index.js, packages/postcss-minify-params/src/index.js
=> test(postcss-minify-params): `@supports` at-rule

packages/postcss-merge-longhand/src/__tests__/borders.js, packages/postcss-merge-longhand/src/lib/decl/borders.js
I have added a guard against missing border-width values which prevents errors while trying to read undefined values.
For example:
```css
.x {
border: 1px solid lightgray;
border-top-width: 0;
border-right-width: 0;
border-bottom-width: 0;
}
```
Missing `border-left-width` causes the following error to be thrown:
```
TypeError: Cannot read property 'toLowerCase' of undefined
```
Fixes:
fixes #743
fixes #718
=> fix(postcss-merge-longhand): guard against missing border-width props

packages/postcss-merge-longhand/src/__tests__/borders.js, packages/postcss-merge-longhand/src/__tests__/boxBase.js, packages/postcss-merge-longhand/src/__tests__/columns.js, packages/postcss-merge-longhand/src/lib/canExplode.js
Closes https://github.com/cssnano/cssnano/issues/769 & https://github.com/cssnano/cssnano/issues/714. Also adds support for the global `revert` keyword.
=> fix(postcss-merge-longhand): Fix crash on empty declarations.

packages/postcss-colormin/package.json, packages/postcss-colormin/script/generate.js
fix #818 
I moved the generate script to an outside folder and changed its module to common js module and using the node runner to build the `keyword.json` instead of `babel-node`
=> fix(postcss-colormin): fixed plugin running error

packages/postcss-reduce-idents/src/__tests__/index.js, packages/postcss-reduce-idents/src/lib/encode.js
=> fix(reduce-idents): improve encode

packages/cssnano/src/__tests__/fixtures.js, packages/postcss-unique-selectors/package.json, packages/postcss-unique-selectors/src/__tests__/index.js, packages/postcss-unique-selectors/src/index.js, packages/postcss-unique-selectors/yarn.lock
fix #777 
- Added `postcss-selector-parser` to filter out the non-comment node types to go through the sorting function.
- added tests to support it 
Update
---
Waiting for parser's mixin support  https://github.com/postcss/postcss-selector-parser/issues/217
=> fix(unique-selector): removed sorting and involving selector comments

packages/postcss-ordered-values/src/__tests__/index.js, packages/postcss-ordered-values/src/index.js, packages/postcss-ordered-values/src/rules/columns.js
Ref #756
- `columns`
In this, they takes two values, `width` and `count`, they both can be numbers and string(auto, inherit, unset etc. ) but `count` can't have `units`, and as per MDN's formal format, `width` should come first. So based on this, the function will change the order only if `unit` are mentioned.
- `column-rule`
should be ordered like `border`
=> chore(ordered-values): added support for columns and column-rule

packages/postcss-ordered-values/src/__tests__/index.js, packages/postcss-ordered-values/src/index.js, packages/postcss-ordered-values/src/lib/joinGridValue.js, packages/postcss-ordered-values/src/rules/grid.js
Ref #756
Added normalization for grid-\*
=> chore: added support for grid-*

packages/postcss-merge-rules/src/__tests__/index.js, packages/postcss-merge-rules/src/index.js
Fixes #824 
And remove some unsafe tests for `all`. Because, for example, in https://github.com/cssnano/cssnano/pull/872/files#diff-b9a0c329a170d3294df84c3c787c690dL624-L626 , the render result is different between input and output.
the input
```css
.a{margin: 10px 20px;display: flex;all: initial;font-size: 10px;border-radius: 2px;color: blue;}.b{margin: 10px 30px;display: flex;all: initial;font-size: 20px;border-radius: 2px;color: blue;}
```
render as
(https://codepen.io/sosukesuzuki/pen/OJPYRoN).
But, the output
```css
.a,.b{display: flex;all: initial;border-radius: 2px;color: blue;}.a{margin: 10px 20px;font-size: 10px;}.b{margin: 10px 30px;font-size: 20px;}
```
render as
(https://codepen.io/sosukesuzuki/pen/MWYdeBK).
=> Don't unsafe merge 'all' declaration

packages/postcss-convert-values/src/__tests__/index.js, packages/postcss-convert-values/src/index.js
Resolving bug in which opacity values defined as percentages are being converted to 1%.
=> Resolve Opacity Bug

.all-contributorsrc, jest.config.js, packages/postcss-convert-values/src/__tests__/index.js, packages/postcss-convert-values/src/index.js
When using `min()`, `max()` or `clamp()`, `0` values get their units stripped, making the value invalid. This pull request preserves any units within these CSS functions.
=> fix: units being removed in math functions

packages/postcss-minify-selectors/src/__tests__/index.js, packages/postcss-minify-selectors/src/index.js
fixes https://github.com/cssnano/cssnano/pull/925
Explanation details : https://github.com/cssnano/cssnano/pull/925#issuecomment-663862095
Ref: [this](https://drafts.csswg.org/selectors-4/?expand=1#attrnmsp)
=> fix(postcss-minify-selectors): added check for node.operator for namespace

packages/cssnano/src/__tests__/issue927.js, packages/postcss-normalize-string/src/__tests__/index.js, packages/postcss-ordered-values/src/index.js
Fixes #927 
`postcss-order-values` when transforming the `columns` was returning ASTs instead of `string`
=> fix(postcss-ordered-values): columns transform returning string instead of the AST

packages/postcss-reduce-initial/README.md, packages/postcss-reduce-initial/src/__tests__/index.js, packages/postcss-reduce-initial/src/index.js
fixes #905 
Added new option `ignore` to skip the property passed in it.
=> feat(postcss-reduce-initial): added ignore options

package.json, yarn.lock
According to the [release notes](https://github.com/lerna/lerna/releases/tag/v4.0.0), the major version bump is for dropping Node.js 6 and 8 support. Otherwise it should be mostly dependency bumps and bug fixes.
=> chore: update lerna to latest major

babel.config.js, package.json, yarn.lock
Moving to PostCSS 8 drops Node.js < 10.13 support, so let's avoid bloating to the generated code by transpiling for older versions.
I've also updated Babel to use the new top-level targets option: https://babeljs.io/blog/2021/02/22/7.13.0
=> chore: transpile only for supported Node.js versions

yarn.lock
Updating Babel in #1011 left Babel 7.12 as Jest dep,
even though Jest allows later versions. I regenerated yarn.lock
from scratch to ensure we use the same Babel version for test and
build. As a side effect this seems to get rid of some other duplicate
dependencies.
=> chore: regenerate yarn.lock and update all deps

packages/postcss-svgo/package.json, packages/postcss-svgo/src/__tests__/index.js, packages/postcss-svgo/src/index.js, packages/postcss-svgo/yarn.lock
Hopefully this will stop further alarmed comments.
=> refactor: remove is-svg

packages/cssnano-preset-advanced/yarn.lock, packages/cssnano-preset-default/yarn.lock, packages/cssnano/yarn.lock, packages/postcss-svgo/package.json, packages/postcss-svgo/src/__tests__/index.js, packages/postcss-svgo/src/index.js, packages/postcss-svgo/yarn.lock
backport of #1034 to the `v4` branch.
closes #1030
=> fix(v4): remove is-svg dependency

packages/cssnano/package.json
Fix #1046
The opencollective package breaks some CI setups,
so replace it with the funding field, the same way as postcss.
=> fix(cssnano): replace opencollective with funding field.

packages/postcss-merge-longhand/src/__tests__/borders.js, packages/postcss-merge-longhand/src/lib/decl/borders.js
=> fix(postcss-merge-longhand): mergeLonghand should not apply to CSS variables

packages/css-size/package.json, packages/css-size/src/index.js, packages/css-size/yarn.lock
After updating the C++ compiler, I could not build the `brotli-size` package required by css-simple any more because. I updated `brotli-size` and a bunch of other dependencies that were stuck on very old versions, which gets rid of a boatload of transitive dependencies. The only change of note is that some dependencies now require Node.js 10,x, but it does not change anything for us since we required Node.js 10 already.
Here's a summary of the major dependency changes:
* `brotli-size`: require Node.js 10.x [changelog](https://github.com/erwinmombay/brotli-size/releases)
* `gzip-size`: require Node.js 10.x [changelog](https://github.com/sindresorhus/gzip-size/releases)
* `round-precision`: removed and inlined the code instead. This package has two dependencies of its own, but all it does …
=> chore(css-size): update dependencies

packages/cssnano/src/__tests__/postcss-minify-selectors.js, packages/postcss-minify-selectors/package.json, packages/postcss-minify-selectors/src/__tests__/index.js, packages/postcss-minify-selectors/src/index.js, packages/postcss-minify-selectors/src/lib/canUnquote.js, packages/postcss-minify-selectors/src/lib/unquote.js, packages/postcss-minify-selectors/yarn.lock
Replace the old selector parser release used by `postcss-minify-selectors` so all packages use the new `postcss-selector-parser` 6.0.0 release.
I have tried to follow the postcss-selector parse [API docs](https://github.com/postcss/postcss-selector-parser/blob/master/API.md) but I was forced to operate on raw attribute values since the automatic quotes removal introduced in postcss-selector-parser 4.0 does not seem to work well in some cases (see https://github.com/postcss/postcss-selector-parser/pull/245).
=> postcss-minify-selectors: update selector parser

util/buildFrameworks.js
Change the import prefix to a relative path (leftover from #1061).
=> chore: fix the code to generate the integration test fixtures

packages/postcss-colormin/package.json, packages/postcss-colormin/yarn.lock
Fixes #1110
See discussion https://github.com/omgovich/colord/issues/51
=> fix(postcss-colormin): Get rid of ERR_PACKAGE_PATH_NOT_EXPORTED error

packages/cssnano-preset-advanced/CHANGELOG.md, packages/cssnano-preset-advanced/package.json, packages/cssnano-preset-default/CHANGELOG.md, packages/cssnano-preset-default/package.json, packages/cssnano/CHANGELOG.md, packages/cssnano/package.json, packages/postcss-colormin/CHANGELOG.md, packages/postcss-colormin/package.json, site/docs/changelog.md
* postcss-colormin 5.1.1
* cssnano-preset-default 5.1.1
* cssnano-preset-advanced 5.1.1
Please check carefully that the version numbers match.
This time I generated the changelog by hand as lerna keeps repeating the same changelog entries over and over again and I cannot understand why it bumbs version numbers for packages where nothing changes. We need to find some other solution as lerna is somewhat unmaintained.
=> Publish cssnano 5.0.4

packages/postcss-svgo/src/__tests__/index.js, packages/postcss-svgo/src/index.js
=> fix(postcss-svgo): skip non-SVG urls

packages/cssnano-preset-advanced/package.json, packages/cssnano-preset-default/package.json, packages/cssnano/CHANGELOG.md, packages/cssnano/package.json, packages/postcss-colormin/CHANGELOG.md, packages/postcss-colormin/package.json, packages/postcss-merge-rules/CHANGELOG.md, packages/postcss-merge-rules/package.json, packages/postcss-svgo/CHANGELOG.md, packages/postcss-svgo/package.json
Again I've bumped every version and wrote the changelog manually. 
I've tried [changesets](https://github.com/atlassian/changesets/) but I was not happy. Either it did not want to bump cssnano when you bump the single plugins or it would bump everything to the highest version (see [this example in the emotion repo](https://github.com/emotion-js/emotion/commit/3a8eaac14c1d157d0b5bb96597444e05f4c33eb1), where some packages jump from `x.1` to `x.4`)
=> Publish cssnano 5.0.5

packages/postcss-normalize-url/package.json, packages/postcss-normalize-url/src/index.js, yarn.lock
* turn off `stripTextFragment` to preserve current behavior
normalize-url changelog
https://github.com/sindresorhus/normalize-url/releases
* the major bump from 4 to 5 is for requiring Node.js 10
* the major bump from 5 to 6 is for adding the `stripTextFragmentOption`
=> chore(postcss-normalize-url): bump normalize-url dependency to 6.0.1

packages/cssnano-preset-advanced/CHANGELOG.md, packages/cssnano-preset-advanced/package.json, packages/cssnano-preset-default/CHANGELOG.md, packages/cssnano-preset-default/package.json, packages/cssnano/CHANGELOG.md, packages/cssnano/package.json, packages/postcss-normalize-url/CHANGELOG.md, packages/postcss-normalize-url/package.json, packages/postcss-ordered-values/CHANGELOG.md, packages/postcss-ordered-values/package.json
I think we should make a release to fix https://github.com/cssnano/cssnano/issues/1123, especially since we might need to soon make another one to stop the [npm audit messages coming from a svgo dependency](https://github.com/svg/svgo/pull/1485).
=> Publish cssnano 5.0.6

package.json, site/docs/changelog.md, site/docusaurus.config.js, site/package.json, site/yarn.lock, yarn.lock
* update all website deps
* add back remark-heading-gap dep, which was removed by mistake
About `remark-ehading-gap`, when I prepared https://github.com/cssnano/cssnano/pull/1145  used `ripgrep` to search for unused deps, but it ignores dotfiles by default, so it did not see it was used in `.remarkrc.js`.
=> docs: update website for 5.0.6

packages/postcss-svgo/package.json, yarn.lock
This pull request aims to bump `postcss-svgo`'s dependency of `svgo` from `^2.3.0` to `^2.3.1` 
`svgo` version [2.3.1](https://github.com/svg/svgo/releases/tag/v2.3.1) bumps its dependency on `css-select` from `^3.1.2` to `^4.1.3` in order to bump the transitive dependency `css-what` from 4.x to `^5.0.1`. This addresses a [ReDoS security vulnerability](https://app.snyk.io/vuln/SNYK-JS-CSSWHAT-1298035) present in prior versions.
=> chore(deps): bump postcss-svgo dep of svgo from v2.3.0 to 2.3.1

site/src/components/editor/editor.module.css, site/src/components/editor/inputError.js, site/src/pages/playground.js
This pull request aims to fix the playground WSOD reported in #991
I found two related issues leading to this behaviour:
1. Uncaught errors thrown by `prettier.format()` when the "Format" button is used.
2. The error object from caught postcss errors when using "Run" were being passed to `setOutput()` in order to output it to the output pane of the playground. Here it was passed in raw as `EditorProps.value` - which expected a string, not an object.
The two cases throws slightly different types of errors. 
On most syntax errors, Prettier throws a `SyntaxError` wrapping some output from `CssSyntaxError` thrown by the css parser - which is quite verbose with numbered line output and such in the message. There are also some edge cases causing Prettier to throw different types of errors.  And …
=> fix(site-playground): add missing error handling to fix WSOD (#991)

jest.config.js, packages/cssnano-utils/src/__tests__/sameParent.test.js, packages/cssnano/src/__tests__/api.js, packages/cssnano/src/__tests__/issue26.js, packages/cssnano/src/__tests__/issue927.js, packages/cssnano/src/__tests__/postcss-normalize-url.js, packages/postcss-minify-selectors/src/__tests__/index.js, packages/stylehacks/src/__tests__/api.js, packages/stylehacks/src/__tests__/issue8.js
This pull request aims to address some minor issues leading to warnings during test running.
A sample of the 3 different types of warnings encountered:
It also adds ignores for two test helper files which had ignore patterns for test running but not coverage reporting.
=> test: fix misc. test warnings

.gitignore, site/.gitignore
This pull request aims to re-organise the projects `.gitignore` to help keep it clean, and to add various common editor generated folders/files to the list. It also removes some redundant lines from the site/docusaurus `.gitignore`, which are covered by the root.
The pattern `*.bundle.js` is also deleted.
_(From what I could gather this was added ~5 years ago for a compiler that is now deprecated and no longer used)_
I generated a `.vscode/launch.json` file for the vscode debugger while working on a PR, and thought it would be practical for developers to avoid having to stash or delete these types of files between commits. So I wanted to suggest adding common ignores for the most popular IDEs. Which seemed like a good opportunity for some housekeeping =)
=> chore(git): clean up .gitignore files

packages/cssnano/package.json, packages/cssnano/src/__tests__/config_loading/.cssnanorc.json, packages/cssnano/src/__tests__/config_loading/config-loading.js, packages/cssnano/src/index.js, site/docs/config-file.mdx, yarn.lock
This PR does two things.
First, I've reworked the documentation to mention the config file priorities and added some tests to verify the basic config loading.
In a separate commit, I've replaced cosmiconfig with [lilconfig](https://github.com/antonk52/lilconfig). This gets rid of 22 dependencies and about 1MB when doing `npm i cssnano`.  This makes cssnano use the same library as the lastest postcss-load-config (https://github.com/postcss/postcss-load-config/commit/d1478640e823b5432b7dc43a0ba6e23c58b7b981).
You can't see the removed dependencies in the repository `yarn.lock` because lerna depends on cosmiconfig.
=> Improve config documentation and remove 22 dependencies from cssnano

packages/postcss-reduce-initial/package.json
This pull request aims to fix an outdated babel `--ignore` for the `postcss-reduce-initial` acquire script
It was overlooked in #1169
=> chore(postcss-reduce-initial): fix build command

packages/cssnano/CHANGELOG.md, packages/cssnano/package.json, site/docs/changelog.md
I'd like to publish a new version of the `cssnano` package so people start using the config loading changes in https://github.com/cssnano/cssnano/pull/1168 , in the unlikely case it breaks something.
=> Publish cssnano 5.0.7

yarn.lock
Update all dependencies. A recurring ritual to prevent accumulating Dependabot PRs.  It also happens to remove some packages (1377 additions vs 1581 deletions)
=> chore: regenerate yarn.lock

packages/postcss-minify-gradients/package.json, packages/postcss-minify-gradients/src/__tests__/isColorStop.js, packages/postcss-minify-gradients/src/index.js, packages/postcss-minify-gradients/src/isColorStop.js, yarn.lock
Get rid of 7 dependencies in a cssnano install.
is-color-stop duplicates functionality available from other dependencies. It copies
unit parsing code directly from postcss-value-parser.
cssnano has color detection logic is already available in colord.
Bringing the code inside might also help #650
=> chore(postcss-minify-gradients): replace is-color-stop with own code

packages/css-size/package.json, yarn.lock
Bug fixes and dropping Node.js 8 compat only: https://github.com/cli-table/cli-table3/blob/master/CHANGELOG.md
=> chore(css-size): update cli-table3

site/docs/advanced-transforms.mdx
Add the word import to a sentence.
=> Fix typo: missing word

packages/postcss-merge-longhand/src/__tests__/borders.js, packages/postcss-merge-longhand/src/lib/decl/borders.js
Fix #1217
Before we skipped if the diff was larger than 1, this excluded the case where the diff is 0.
Actually if the declarations are identical this part of the code should probably never execute in
the first place, but the issue only triggers with very specific CSS combinations so I could not
find a different fix.
=> fix(postcss-merge-longhand): skip processing if diff not exactly 1

packages/cssnano-preset-advanced/CHANGELOG.md, packages/cssnano-preset-advanced/package.json, packages/cssnano-preset-default/CHANGELOG.md, packages/cssnano-preset-default/package.json, packages/cssnano/CHANGELOG.md, packages/cssnano/package.json, packages/postcss-merge-longhand/CHANGELOG.md, packages/postcss-merge-longhand/package.json
Bring out the fix for https://github.com/cssnano/cssnano/issues/1217 since it's a crash.
=> Publish cssnano 5.0.10

packages/postcss-merge-rules/package.json, packages/postcss-merge-rules/src/lib/ensureCompatibility.js, packages/postcss-minify-params/package.json, packages/postcss-minify-params/src/index.js, packages/postcss-unique-selectors/package.json, packages/postcss-unique-selectors/src/index.js, yarn.lock
After the recent vulnerability disclosures, I've looked at whether we could further reduce cssnano deps. 
1. we can remove uniqs as it's a one-liner.  The Set method should work on Nodejs 8+ and according to the measurements I have found online it is not slower than array filtering
2. we can remove vendors as it is [a single array](https://github.com/wooorm/vendors/blob/main/index.js) we only use once and it has not changed in the last 5 years, except that the latest release has become ESM-only
=> refactor: drop one-liner dependencies

packages/cssnano/src/__tests__/issue315.js, packages/cssnano/src/__tests__/issue420.js, packages/postcss-normalize-url/src/__tests__/index.js, packages/postcss-normalize-url/src/index.js
Close #843
Close #812
Sorting the parameters calls URL.searchParams.sort() under the hood,
which uses the WHATWG specification for deciding which characters to encode.
The WHATWG is different from the IETF URI spec, so sorting the parameters
causes the URL to be encoded differently.
See (https://nodejs.org/docs/latest-v16.x/api/url.html#class-urlsearchparams)
Add test to check for slashes in URL parameters.
=> fix(postcss-normalize-url): disable URL parameter sorting

package.json, packages/postcss-normalize-charset/src/__tests__/index.js, yarn.lock
I don't think this postcss-devtools has any effect now.
According to its README, postcss-devtools is supposed to measure the running time
of individuals plugins. postcss-devtools has not been updated since PostCSS 5.
It was used in a single test but the test does not inspect the running time
and I can't see the running time in the test output either.
=> chore: remove postcss-devtools

package.json, site/package.json, site/yarn.lock
It's used in sit/util/buildMetadata.mjs
=> chore: move camelcase dependency declaration

.github/workflows/test.yml, package.json, yarn.lock
Not used in the current Jest config. See https://github.com/jest-community/jest-junit If it was used, it should be configured in either `jest.config.js` or at the command line.
=> chore: remove unused junit reporter

packages/css-size/package.json, packages/css-size/src/index.js, yarn.lock
Using the Node.js standard library directly is as convenient.
These packages bundle a bunch of ways to call the standard library functions (ex. on a stream, with promises, sync). They set the maximum compression level by default. Then they return `length` or `byteLength` of the result buffer (`byteLength` === `length` because a Node.js `Buffer` is a  subclass of `UInt8Array` https://nodejs.org/api/buffer.html#buffer).
=> chore(css-size): drop gzip-size and brotli-size deps

packages/postcss-svgo/src/__tests__/index.js
Remove warning "extendDefaultPlugins utility is deprecated" during test run.
Could not find any usage outside of test.
=> test(postcss-svgo): use new SVGO plugins API

.c8rc.json
Add lconv.info output. Codecov fails to parse the JSON output, let's see if this works.
=> ci: fix coverage report format

package.json, site/package.json, site/util/getPackages.mjs, site/yarn.lock, util/buildFrameworks.mjs, yarn.lock
We're just listing directory contents, no need for globs.
=> chore: remove glob from dev dependencies

packages/postcss-normalize-url/package.json, packages/postcss-normalize-url/src/index.js, yarn.lock
is-absolute-url has become ESM only. It boils down to two
short regexes, so we can inline it.
The license is MIT which is the same as cssnano.
=> chore(postcss-normalize-url): inline is-absolute-url dep

example-cli-usage/package.json
This is supposed to be an example of setting up a project for the end
user, so postcss should be installed as a dependency.
=> fix(example): move postcss to dependencies

site/docusaurus.config.js, site/package.json, site/src/pages/playground.js, site/src/pages/styles.module.css, site/yarn.lock
Fix #1162 
* Fix preset selection. Use a dropdown to avoid having to parse the config
* No more red squiggles/scrunched minimap in the editors
* Switch to CodeMirror as Monaco requires to customize the webpack config or use a separate loader. Total Playground size drop by about 3Mb as CodeMirror is lighter weight
* Do not save the playground state in local storage (it broke URL sharing since the local storage config was always loaded first. Besides, I don't see the use of saving the work in the playground on your local computer over multiple sessions)
* The Docusaurus light/dark switch also influences the editor colors, so I have fixed the editor theme to make sure it remains legible. Ideally the dark/light switch on Docusaurus should also switch the editor, but I could not find a way to …
=> docs: update site and improve playground

packages/postcss-colormin/src/__tests__/minifyColor.js, packages/postcss-colormin/src/index.js, packages/postcss-colormin/src/minifyColor.js
Allow passing `colord` lib options to `postcss-colormin`.
Created from #1262
=> feat: allow options in colormin

packages/postcss-colormin/src/index.js, packages/postcss-merge-rules/src/index.js, packages/postcss-merge-rules/src/lib/ensureCompatibility.js, packages/postcss-minify-font-values/src/index.js, packages/postcss-minify-selectors/src/index.js, packages/postcss-normalize-display-values/src/index.js, packages/postcss-normalize-positions/src/index.js, packages/postcss-normalize-string/src/index.js, packages/postcss-normalize-timing-functions/src/index.js, packages/postcss-normalize-unicode/src/index.js, packages/postcss-normalize-whitespace/src/index.js, packages/postcss-ordered-values/src/index.js, packages/postcss-reduce-transforms/src/index.js
Fix a surprising issue when trying to generate types. 
Prevent TypeScript from sometimes inferring the type of cache as {}, which sometimes prevent setting a cache value even in non-strict mode.
I think `Map()` is clearer when you read the code.
=> refactor: use Map as cache instead of object

util/getData.js
getData() was used to test getMatch() the we've removed in #1279.
=> test: remove unused test helper

packages/postcss-discard-comments/src/index.js
Help TypeScript infer the right type for the cache.
=> refactor(postcss-discard-comments): use map instead of object as cache

packages/cssnano-preset-advanced/src/__tests__/autoprefixer.js, packages/cssnano-preset-advanced/src/__tests__/integrations.js, packages/cssnano-preset-default/src/__tests__/css-declaration-sorter.js, packages/cssnano-preset-default/src/__tests__/integrations.js, packages/cssnano-preset-lite/src/__tests__/index.js, packages/cssnano-preset-lite/src/__tests__/integrations.js, packages/postcss-colormin/src/__tests__/index.js, packages/postcss-discard-empty/src/__tests__/index.js, packages/postcss-minify-font-values/src/__tests__/index.js, packages/postcss-normalize-whitespace/src/__tests__/index.js, util/integrationTestHelpers.js, util/testHelpers.js
Separate test helpers from integration test helpers,
so we can run most tests without loading the cssnano package,
which causes loading cssnano-preset-default and so most of the repository.
I noticed this issue because pointing the `main` field to the wrong file in the
package.json of postcss-normalize-timing-functions
causes every test to fail even it does not depend on postcss-normalize-timing-functions.
=> test: reduce circular dependencies in tests

packages/cssnano-utils/LICENSE, packages/cssnano-utils/package.json, packages/postcss-minify-font-values/package.json, packages/postcss-minify-params/package.json, packages/postcss-normalize-charset/package.json
The MIT license requires including the full license text.
=> docs: add missing license

packages/postcss-minify-selectors/src/index.js, packages/postcss-normalize-positions/src/__tests__/index.js, packages/postcss-normalize-positions/src/index.js, packages/postcss-normalize-string/src/index.js, packages/postcss-reduce-transforms/src/index.js
* use maps instead of objects when the object is only used as a map
* make function dispatching a little more explicit.
* test: add one test for uncovered case in background positions
=> refactor: replace objects with maps and avoid excessively dynamic code

packages/postcss-discard-duplicates/src/index.js
No need to use a map because there's only two options.
This way we also get rid of the empty 'noop' function.
=> refactor(postcss-discard-duplicates): reduce indirection

packages/postcss-convert-values/src/lib/convert.js
- lower case unit once
- if unit is one no need to multiply or divide
=> refactor(postcss-convert-values): remove unnecessary steps

packages/postcss-minify-gradients/src/__tests__/isColorStop.js, packages/postcss-minify-gradients/src/isColorStop.js, packages/postcss-minify-selectors/src/index.js, packages/postcss-zindex/src/index.js
- `postcssValueParser.unit()` [returns the number as a string](https://github.com/TrySound/postcss-value-parser/blob/11a4436e74930f4eaf9cbdb2063656bcce8ebf6a/lib/unit.js#L117), so checking against `0` will always fail
- It's `rawSpaceAfter` with just one `s`. It seems to make no difference in the tests though
- in postcss-zindex, `LayerCache` constructor does not take parameters
=> fix: fix bad parameters and conversions

packages/postcss-minify-gradients/src/index.js
Explicitly convert numbers to strings before assigning them to a
node value, so it's clearer how to compare them.
=> fix(postcss-minify-gradients): handle node values as strings

packages/postcss-discard-unused/src/index.js, packages/postcss-minify-font-values/src/lib/minify-family.js, packages/postcss-minify-params/src/index.js
- avoid assigning different types to the same variable
- pass explicit 0 argument to `charCodeAt()`
- avoid implicitly converting back and forth between string and number
=> refactor: improve types

packages/stylehacks/src/index.js, packages/stylehacks/src/plugin.js, packages/stylehacks/src/plugins/bodyEmpty.js, packages/stylehacks/src/plugins/htmlCombinatorCommentBody.js, packages/stylehacks/src/plugins/htmlFirstChild.js, packages/stylehacks/src/plugins/important.js, packages/stylehacks/src/plugins/leadingStar.js, packages/stylehacks/src/plugins/leadingUnderscore.js, packages/stylehacks/src/plugins/mediaSlash0.js, packages/stylehacks/src/plugins/mediaSlash0Slash9.js, packages/stylehacks/src/plugins/mediaSlash9.js, packages/stylehacks/src/plugins/slash9.js, packages/stylehacks/src/plugins/starHtml.js, packages/stylehacks/src/plugins/trailingSlashComma.js
- replace the mix of closures and `.apply()` with `extends`
- replace rest parameters with single arguments because
plugin methods are only called with one node as argument
=> refactor(stylehacks): use standard JavaScript subclasses

packages/postcss-merge-longhand/src/lib/decl/columns.js, packages/postcss-minify-gradients/src/isColorStop.js, packages/postcss-svgo/src/index.js, packages/postcss-unique-selectors/src/index.js
- selector parser callback is not expected to return a node
- unit() returns false if it cannot parse
- don't assign an array of nodes to a string
=> refactor: conform to type signatures

packages/postcss-discard-unused/src/index.js, packages/postcss-normalize-string/src/index.js, packages/postcss-normalize-unicode/src/index.js, packages/postcss-ordered-values/src/lib/getValue.js, packages/postcss-ordered-values/src/rules/animation.js, packages/postcss-ordered-values/src/rules/boxShadow.js, packages/postcss-ordered-values/src/rules/transition.js, packages/stylehacks/src/index.js
Refactor functions that don't conform to reducer conventions,
as they return a different type than the initial array contents,
modify external variables or stop processing halfway.
=> refactor: rewrite unusual reducers as loops

site/package.json, site/pnpm-lock.yaml
Fix #1311
Somehow the last patch release does not run when bundled with webpack.
cc @Siilwyn
=> docs: downgrade css-declaration-sorter in playground

packages/postcss-ordered-values/src/lib/getValue.js, packages/stylehacks/src/plugins/leadingStar.js
- replace some with forEach when return value is ignored
- pass a Node array instead of a fake Node to stringify
=> refactor: replace bad types

packages/postcss-merge-longhand/src/lib/decl/borders.js, packages/postcss-merge-longhand/src/lib/decl/boxBase.js, packages/postcss-merge-longhand/src/lib/decl/columns.js
There is no named export from the stylehacks package, so the named import
only works when both all packages are transpiled to CJS.
=> chore(postcss-merge-longhand): fix stylehacks import

packages/css-size/src/__tests__/index.js
After moving from dist to src, the path to the 'cli' file was not adjusted properly in the test.
I find a bit discomforting that the tests were exiting without result instead of failing.
=> test(css-size): fix cli path

package.json
There's no prepare any more since the source is published as is.
=> fix: remove deleted step from publish script

site/package.json, site/pnpm-lock.yaml, site/util/buildMetadata.mjs, site/util/buildSiteMarkdown.mjs, site/util/sortAscending.mjs
* The default array sort is ascending, so passing this function
makes no difference. I've compared the generated files to check
* @iarna/toml writes an reads, is 60 kB smaller and supports
a more recent toml version
=> chore(docs): remove sortAscending function

packages/postcss-reduce-initial/README.md
They switched to Creatice Commons Zero in 2018 https://github.com/mdn/data/blob/main/LICENSE
I cannot find that the CSSDATA template mentioned in the original README
is used anywhere in the code right now and the template does not exist
on MDN any more either.
=> chore: fix license of of Mozilla data

packages/postcss-merge-idents/src/index.js, packages/postcss-reduce-idents/src/lib/counter-style.js, packages/postcss-reduce-idents/src/lib/counter.js, packages/postcss-reduce-idents/src/lib/grid-template.js, packages/postcss-reduce-idents/src/lib/keyframes.js, packages/stylehacks/src/plugins/important.js
-  chore(postcs-reduce-idents): replace array with Set
-  chore(postcss-reduce-idents): don't access node properties before narrowing node type
-  chore(postcss-merge-idents): turn parameter into constant
-  fix(stylehacks): check if match index exists
=> chore: fix some type issues in the advanced presets plugins

packages/cssnano-preset-advanced/src/index.js, packages/cssnano-preset-advanced/types/index.d.ts, packages/cssnano-preset-lite/src/index.js, packages/cssnano-preset-lite/types/index.d.ts
Declare the function before assigning it to an export to fix
`An export assignment cannot be used in a module with other exported elements`
=> fix: fix TypeScript error when importing lite and advanced presets

packages/cssnano-preset-advanced/CHANGELOG.md, packages/cssnano-preset-advanced/package.json, packages/cssnano-preset-lite/CHANGELOG.md, packages/cssnano-preset-lite/package.json
cssano-preset-lite and cssnano-preset-advanced are not cssnano dependencies so I don't think it makes sense to bump cssnano too.
=> Publish preset TypeScript fixes

.github/workflows/test.yml
The jobs complete fine without any extra permission, so we can improve security by disabling them (as the [Open Source Security Foundation scorecard](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions) recommends). Someone with administrative access can also change the default permissions for all workflows in the repository, in that case the individual workflows need to opt-in. Also see the [GitHub docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions).
=> chore: disable most permissions for the CI job runner

packages/postcss-discard-empty/src/index.js, packages/postcss-discard-empty/test/index.js, packages/postcss-minify-params/src/index.js, packages/postcss-minify-params/test/index.js, packages/postcss-normalize-whitespace/src/index.js, packages/postcss-normalize-whitespace/test/index.js
Fix #1350
Empty custom properties are valid according to the latest spec updates and various CSS tricks use them.
=> fix(postcss-discard-empty): preserve empty custom properties

packages/postcss-merge-longhand/src/lib/parseWsc.js, packages/postcss-merge-longhand/test/borders.js
Fix #847
Locate every custom property inside a value, then build a
new string by preserving the custom properties and lowercasing
the rest.
=> fix(postcss-merge-longhand): preserve custom property case

.eslintrc.json, .prettierignore, package.json, pnpm-lock.yaml
Don't mix formatting with other errors when the editor has prettier integration. The Prettier documentation also recommends against running Prettier as ESlint plugin for the same reason
https://prettier.io/docs/en/integrating-with-linters.html#notes
* use eslint-config-prettier directly instead of plugin-prettier
* ignore all file types except JS
We can't format some of the markdown because it's generated, the same goes for YAML files and *d.ts. Most of the CSS is also from third-party libraries.
=> chore: update prettier config

packages/postcss-reduce-idents/src/lib/grid-template.js, packages/postcss-reduce-idents/test/index.js
* fix issue where uppercase special values (AUTO) were transformed
* skip useless parsing of `grid-template-rows` and `grid-template-columns` as no substitutions occur there (the code always checks whether the token type is `string` before considering a candidate for replacing, so there was not bug but the intents was confusing)
=> fix(postcss-reduce-idents): fix handling of reserved keywords

packages/cssnano-preset-advanced/CHANGELOG.md, packages/cssnano-preset-advanced/package.json, packages/cssnano-preset-default/CHANGELOG.md, packages/cssnano-preset-default/package.json, packages/cssnano-preset-lite/CHANGELOG.md, packages/cssnano-preset-lite/package.json, packages/cssnano/CHANGELOG.md, packages/cssnano/package.json, packages/postcss-merge-idents/CHANGELOG.md, packages/postcss-merge-idents/package.json, packages/postcss-merge-longhand/CHANGELOG.md, packages/postcss-merge-longhand/package.json, packages/postcss-merge-rules/CHANGELOG.md, packages/postcss-merge-rules/package.json, packages/postcss-minify-gradients/CHANGELOG.md, packages/postcss-minify-gradients/package.json, packages/postcss-minify-params/CHANGELOG.md, packages/postcss-minify-params/package.json, packages/postcss-ordered-values/CHANGELOG.md, packages/postcss-ordered-values/package.json
Re-release all packages that depend on at least another workspace package, to fix https://github.com/cssnano/cssnano/pull/1372 (besides cssnano and the presets, it includes all packages that depend on cssnano-utils or stylehacks).
=> Publish cssnano 5.1.5

packages/postcss-merge-longhand/src/lib/mergeRules.js, packages/postcss-merge-longhand/test/borders.js
The previous algorithm was to pop values off the end and comparing to
the other given property. Change the detection to instead check that all
the components of the second value are in the first value.
Fixes #1375
Please note that I'm new to this codebase, so I may very well have missed something. The existing tests do pass though.
=> fix: conflict detection needs to consider border-left-color vs border-color

package.json, packages/postcss-merge-longhand/types/lib/decl/index.d.ts, packages/postcss-merge-longhand/types/lib/trbl.d.ts, packages/stylehacks/types/plugins/index.d.ts, pnpm-lock.yaml
TypeScript adds `flat()`, `flatMap()` and `flat()` to type definitions
for modules that export an array.
These only exist in Node since Node 11, butI don't think that's a problem
because they're in internal modules.
=> chore: update TypeScript and regenerate types

packages/cssnano-preset-default/package.json, pnpm-lock.yaml, site/package.json, site/pnpm-lock.yaml
Drop timsort dependency and fix issues with imports. [Changelog](https://github.com/Siilwyn/css-declaration-sorter/blob/master/changelog.md)
=> chore(cssnano-preset-default): update css-declaration-sorter

packages/cssnano-preset-advanced/CHANGELOG.md, packages/cssnano-preset-advanced/package.json, packages/cssnano-preset-default/CHANGELOG.md, packages/cssnano-preset-default/package.json, packages/cssnano/CHANGELOG.md, packages/cssnano/package.json, packages/postcss-merge-longhand/CHANGELOG.md, packages/postcss-merge-longhand/package.json
The previous release (5.1.6) did not update `postcss-merge-longhand` version and publish a  new `postcss-merge-longhand` with the fixes but only updated the presets version number.
=> chore: really publish the postcss-merge-longhand changes

site/package.json, site/pnpm-lock.yaml, site/src/playground.njk
Update both the playground dependencies and the build tools. Browsersync (eleventy dependencies) updated socket.io from 2 to 4 in a patch release, which gets rid of a bunch of unmaintained dependencies, which explains the diff in the lockfile.
=> docs: update website dependencies

packages/postcss-merge-longhand/src/lib/decl/borders.js, packages/postcss-merge-longhand/src/lib/decl/boxBase.js, packages/postcss-merge-longhand/src/lib/decl/columns.js, packages/postcss-merge-longhand/src/lib/remove.js
I find this function makes the code harder to read, because it just
calls `remove()` on the PostCSS node, but the fact that it's a separate
function makes you believe that it's performing a more complex operation. It also returns the node, but nothing uses the return value.
=> refactor(postcss-merge-longhand): delete remove() function

package.json, packages/postcss-ordered-values/package.json, packages/postcss-ordered-values/script/buildListStyleType.js, packages/postcss-reduce-initial/package.json, packages/postcss-reduce-initial/script/acquire.mjs, packages/postcss-reduce-initial/script/test/io.mjs, pnpm-lock.yaml
* correct the file paths that changed when transpiling was
removed and TypeScript checks added
* switch fetch library to undici since its got zero dependencies
and it's going to be the basis for built-in Node.js fetch
* did not commit changes to the data files from running the scripts
again because they need a separate review for browser compatibility
=> fix: correct file paths in scripts that fetch external data

.github/workflows/test.yml
Node.js 18 will become the next LTS but 17
reaches end-of-life at the end of May.
=> chore: use Node.js 18 instead of 17 in CI

package.json, packages/postcss-convert-values/package.json, packages/postcss-convert-values/src/index.js, packages/postcss-convert-values/types/index.d.ts, pnpm-lock.yaml
Follow-up to #1385
Use browserslist to determine whether browsers include IE 11 as discussed in https://github.com/cssnano/cssnano/pull/1385#issuecomment-1094909660
=> feat(postcss-convert-values): preserve min-width percent on IE 11 only

packages/postcss-merge-longhand/src/lib/decl/borders.js, packages/postcss-merge-longhand/test/borders.js
=> fix(postcss-merge-longhand): preserve fallback for color() function

packages/cssnano-preset-advanced/CHANGELOG.md, packages/cssnano-preset-advanced/package.json, packages/cssnano-preset-default/CHANGELOG.md, packages/cssnano-preset-default/package.json, packages/cssnano/CHANGELOG.md, packages/cssnano/package.json, packages/postcss-merge-longhand/CHANGELOG.md, packages/postcss-merge-longhand/package.json
I would release this to avoid other issues similar to https://github.com/cssnano/cssnano/issues/1396 because it's going to take some time to properly refactor color handling as it's duplicated multiple times across the codebase. In fact, before working on any more issues, I am thinking to start a branch to merge plugins and reduce the number of traversals like we said many times in the past. That should a give a clearer picture of how many times the same properties are parsed and analysed in separate places.
=> Publish cssnano 5.1.9

.github/workflows/test.yml
Unblock the pipeline by updating the @pnpm/action-setup. We need this commit: https://github.com/pnpm/action-setup/pull/46 to stop CI from failing when trying to install pnpm on MacOS
=> chore: update GitHub action versions

packages/cssnano/test/_processCss.js, packages/cssnano/test/postcss-colormin.js, packages/cssnano/test/postcss-minify-font-values.js, packages/cssnano/test/postcss-normalize-whitespace.js, packages/postcss-colormin/test/index.js, packages/postcss-discard-empty/test/index.js, packages/postcss-minify-font-values/test/index.js, packages/postcss-normalize-whitespace/test/index.js
Most tests that exercise the default preset as a whole were in the
cssnano directory, but some were mixed with the individual plugin tests.
* To distinguish the effect of each individual plugin, move all
remaining integration tests in the cssnano test directory.
* Convert tests that only check the effect of a single plugin,
to only use that plugin.
This will make it easier to experiment with merging plugins.
The number of tests stays the same. There are 2383 tests before and after the change.
=> test: separate integration tests from single plugin tests

packages/postcss-normalize-positions/src/index.js, packages/postcss-normalize-positions/test/index.js, packages/postcss-normalize-repeat-style/src/index.js, packages/postcss-normalize-repeat-style/test/index.js, packages/postcss-ordered-values/src/index.js
* refactor: use the same variable functions definition everywhere
* refactor(postcss-ordered-values): extract variable functions set
=> refactor: extract CSS variable indentifiers

packages/postcss-merge-longhand/src/lib/parseWsc.js, packages/postcss-merge-longhand/test/borders.js
Extends the regex that is used to locate custom properties inside a
value so that their case is preserved to also preserve the case of
custom property names that contain hyphen-minus characters.
For example, the case of the custom property in the following rule
should be preserved:
```css
border: 1px solid rgba(var(--colors-secondaryColor));
```
In our projects, we use CSS custom property names with hyphen-minus characters. These custom property names were lowercased via `postcss-merge-longhand` when minifying for production. Since hyphen-minus characters are valid in CSS custom property names, I think they should be allowed in the corresponding regex so that the case of hyphenated custom properties is preserved.
Please check if any of these apply:
=> fix(postcss-merge-longhand): preserve hyphenated custom property case

packages/cssnano/src/index.js, packages/cssnano/types/index.d.ts
Invoking `postcss` gives you a Processor, not a Plugin.
=> Fix `cssnanoPlugin` type to return Processor not Plugin

packages/cssnano/CHANGELOG.md, packages/cssnano/package.json
Release the fix for https://github.com/cssnano/cssnano/pull/1425 to make it possible to call `cssnano.process()` in TypeScript.
=> Publish cssnano 5.1.13

.github/workflows/test.yml, package.json, pnpm-lock.yaml
Update development dependencies and GitHub actions. The changesets/cli update brings in a lot of polyfills so pnpm-lock.yaml increases but we do get rid of Prettier 1.9 and old versions of Chalk from the transitive dependencies dependencies, as well as remove a deprecation warning by bumping  the transitive dependency smartwrap from 1 to 2.
=> chore: update development deps

packages/postcss-reduce-initial/src/data/toInitial.json, packages/postcss-reduce-initial/test/index.js
Fix mask-repeat initial value and fix test that did not catch the issue because the default browserslist query includes opera mini which does not support initial.
Fix #1452
=> fix(postcss-reduce-initial): fix mask-repeat conversion

packages/postcss-colormin/src/index.js, packages/postcss-colormin/test/index.js
I skimmed through all [CSS properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference#index) related to `@font-face` and it looks like only [`src`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/src) is impacted by this bug.
Fixes #1463
=> fix(postcss-colormin): don't minify colors in `src` declarations

example-cli-usage/package.json, package.json, packages/postcss-discard-comments/package.json, packages/postcss-merge-rules/package.json, pnpm-lock.yaml
Update the dependencies used in the integration tests to the latest version which do not support Node.js 10 and 12.
Update the example CLI project to the latest postcss-cli version.
=> test: update integration test deps

package.json, packages/postcss-merge-rules/src/index.js, packages/stylehacks/types/plugins/index.d.ts, pnpm-lock.yaml
I've updated to 5.0.2 directly since it's been released in the meantime. No changes except one parameter type change.
=> chore: update TypeScript to 5.0.2

packages/cssnano/test/presets.js, packages/postcss-reduce-initial/src/index.js, packages/postcss-reduce-initial/types/index.d.ts
Fix #1436
Ensure options are read also when the plugin is configured in cssnano instead as a standalone PostCSS plugin.
=> fix(postcss-reduce-initial): ensure options are always read

packages/postcss-normalize-url/src/normalize.js, packages/postcss-normalize-url/test/normalize.js
This is one of the biggest change for the 6.0 release, so I wanted to go though the tests to ensure I did not introduce any strange behaviour compared to the upstream package.
I think that if this looks fine we can release 6.0.
=> test(postcss-normalize-url): improve normalize-url coverage

packages/postcss-merge-rules/src/index.js, packages/postcss-merge-rules/test/index.js
Add a test for #1489 and ensure container queries do not get merged incorrectly.
=> fix(postcss-merge-rules): preserve container queries

packages/postcss-reduce-idents/src/lib/grid-template.js, packages/postcss-reduce-idents/test/index.js
Handle grid and column names enclosed in square brackets. Cover both the case where the brackets contain a single grid line name and the case where the brackets contain multiple separate grid line names.
Fix #529 (again)
=> fix(postcss-reduce-idents): fix line names grid templates

.github/workflows/test.yml
Since Nodee 19 support will stop on June 1. Also update action and npm version.
=> chore: replace Node.js 19 with Node.js 20 in CI

packages/cssnano-preset-default/package.json, pnpm-lock.yaml
The major bump in css-declaration-sorter is because of dropping support for Node < 14, so it non-breaking for cssnano.
Fix #1502
=> fix(cssnano-preset-default): update css-declaration-sorter

packages/postcss-minify-selectors/src/index.js, packages/postcss-minify-selectors/test/index.js
This PR fixes an issue reported in https://github.com/cssnano/cssnano/issues/1460
Keyframe selectors from scroll-driven animations ([named timeline range name and percentage](https://www.w3.org/TR/scroll-animations-1/#named-range-keyframes)) are mangled by replacing `100%` with `to` in keyframe selectors where it is not valid.
```css
@keyframes test {
entry 100% {
color: red;
}
}
/*
The keyframe-selector with a named timeline range name and percentage is mangled to:
@keyframes test {
entry to {
color: red;
}
}
*/
```
This PR fixes the issue by only replacing `100%` with `to` when the parent selector only has one child node.
=> fix: prevent mangling of 'named timeline range names and percentages' in keyframe selectors

CONTRIBUTORS.md, packages/postcss-convert-values/src/index.js, packages/postcss-convert-values/test/index.js
Fix https://github.com/cssnano/cssnano/issues/1526
In `@property`, when `syntax` is `'<percentage>'`,  `%` is essential.
**Chrome**:
=> fix(postcss-convert-values): keep % unit in @property

packages/css-size/test/index.js
This is the proposed solution for your comment at:
* https://github.com/cssnano/cssnano/pull/1533#issuecomment-1841395155
The result of css-size changes depending on the Node.js version, so rather than testing for a specific number of bytes, this instead asserts that after processing, the result is fewer bytes.
In this scenario, on all Node.js versions except Node.js v20.10.0 (latest LTS release) it returns 67 B, but on v20.10.0 it returns 68 B instead. The new assertion instead asserts what, I assume, was the intent of the test, while passing on all Node.js versions.
=> test: fix api options for node v20.10.0

.github/workflows/publish.yml
Allow to trace an npm tag to a commit in the repo
=> chore: add workflow to publish to npm

package.json, pnpm-lock.yaml
Globals major bump because it requires Node.js 18
=> chore: update development dependencies

.changeset/cyan-squids-own.md, packages/postcss-minify-font-values/src/index.js, packages/postcss-minify-font-values/src/lib/minify-font.js, packages/postcss-minify-font-values/test/minify-font.js, packages/postcss-minify-font-values/types/lib/minify-font.d.ts
When trying to process font value strings with unusual space usage (quoted strings glued to other values), add missing spaces to font property values before minifying so the minification logic does not become too complex.
Also refactor the internal method to take and return a string, so when testing if the transformation work we have readable input and output.
Fix #1519 close #1520
=> Fix minify font space case

packages/cssnano/src/index.js, packages/cssnano/test/plugins_config.js
Thanks for such a brilliant utility 😊
I've fixed a couple of lines in [**packages/cssnano/src/index.js**](https://github.com/cssnano/cssnano/blob/a352df203eebff22f8b3b2ac458fe296474e9bf1/packages/cssnano/src/index.js#L36-L42) where arrays of presets are handled
See how the first preset in an array is assigned to `fn` and `options`?
https://github.com/cssnano/cssnano/blob/a352df203eebff22f8b3b2ac458fe296474e9bf1/packages/cssnano/src/index.js#L36-L42
The lines that follow use `preset` by mistake, rather than `fn`
```patch
+  if (preset.plugins) {
+    return preset.plugins;
-  if (fn.plugins) {
-    return fn.plugins;
}
```
This affects the third example below but is fixed by this PR
```js
cssnano({ // Works ✅
preset: cssnanoPresetDefault({
cssDeclarationSorter: false
})
})
```
```js …
```
=> fix: prevent crash where first preset is already invoked

packages/cssnano-preset-advanced/package.json, packages/cssnano-preset-advanced/src/index.js, packages/cssnano-preset-advanced/types/index.d.ts, packages/cssnano-preset-default/package.json, packages/cssnano-preset-default/src/index.js, packages/cssnano-preset-default/types/index.d.ts, packages/cssnano-preset-lite/src/index.js, packages/cssnano-preset-lite/types/index.d.ts, packages/postcss-colormin/src/index.js, packages/postcss-colormin/src/minifyColor.js, packages/postcss-colormin/types/index.d.ts, packages/postcss-colormin/types/minifyColor.d.ts, packages/postcss-convert-values/src/index.js, packages/postcss-convert-values/types/index.d.ts, packages/postcss-merge-rules/src/index.js, packages/postcss-merge-rules/types/index.d.ts, packages/postcss-minify-params/src/index.js, packages/postcss-minify-params/types/index.d.ts, packages/postcss-normalize-unicode/src/index.js, packages/postcss-normalize-unicode/types/index.d.ts, packages/postcss-reduce-initial/src/index.js, packages/postcss-reduce-initial/types/index.d.ts, packages/stylehacks/src/index.js, packages/stylehacks/types/index.d.ts, pnpm-lock.yaml
While looking at https://github.com/cssnano/cssnano/pull/1570 and https://github.com/alphagov/govuk-frontend/issues/4810 I noticed that plugin type definitions needed updating
This PR fixes a few missing things:
1. Plugin [`postcss-convert-values`](https://www.npmjs.com/package/postcss-convert-values) option `precision` should be optional
1. Plugin [`postcss-colormin`](https://www.npmjs.com/package/postcss-colormin) option `colormin` (via [`cssnano-preset-default`](https://www.npmjs.com/package/cssnano-preset-default)) is typed without property names
1. Plugin [`postcss-reduce-initial`](https://www.npmjs.com/package/postcss-reduce-initial) option `reduceInitial` (via [`cssnano-preset-default`](https://www.npmjs.com/package/cssnano-preset-default)) is not typed
1. Plugin …
=> fix: add missing type declarations to plugins with options

packages/postcss-reduce-initial/src/index.js, packages/postcss-reduce-initial/src/lib/ignoreProps.js, packages/postcss-reduce-initial/test/index.js, packages/postcss-reduce-initial/tsconfig.json, packages/postcss-reduce-initial/types/lib/ignoreProps.d.ts
This PR fixes the `Promise.all()` calls in **packages/postcss-reduce-initial/test/index.js** so they resolve
https://github.com/cssnano/cssnano/blob/c4be0f52a776da12caf0d37e86fc0c194d384e49/packages/postcss-reduce-initial/test/index.js#L20-L25
Two property tests for `'writing-mode'` and `'transform-box'` failed but these were handled in:
* https://github.com/cssnano/cssnano/pull/929
* https://github.com/cssnano/cssnano/pull/1242
=> fix: tests looping `toInitial.json` data should run

packages/cssnano-preset-default/package.json, pnpm-lock.yaml
Updates the package: closes #1588
=> Update to css-declaration-sorter@7.2.0

.changeset/wicked-kings-notice.md, packages/postcss-svgo/package.json, pnpm-lock.yaml
svgo 3.3.0 and 3.3.1 accidentally broke CJS compatibility: https://github.com/svg/svgo/releases
=> chore(postcss-svgo): update svgo version

packages/postcss-discard-comments/package.json, packages/postcss-discard-comments/src/index.js, packages/postcss-discard-comments/test/index.js, pnpm-lock.yaml
Fix #1622
This PR fixes postcss-discard-comments to not strip comment-like strings from selectors.
To fix the issue, I use postcss-selector-parser to ensure that we only strip comments. This change adds a dependency on postcss-selector-parser.
=> fix(postcss-discard-comments): not remove comment-like strings from selectors

packages/cssnano/test/issue1530.js, packages/postcss-minify-selectors/package.json, packages/postcss-minify-selectors/src/lib/canUnquote.js, packages/postcss-minify-selectors/test/index.js, pnpm-lock.yaml
Fix #1530
This PR fixes it by using `cssesc` to additionally check if escaping is needed, and not stripping quotes when escaping is needed.
This PR adds `cssesc` as a dependency, but since it is already a dependency of `postcss-selector-parser`, it is not effectively adding a new dependency.
=> fix(postcss-minify-selectors): quotes are removed even when attribute selector escaping was required

packages/cssnano/test/issue1527.js, packages/postcss-ordered-values/src/rules/animation.js, packages/postcss-ordered-values/test/rules.js
This PR fixes postcss-ordered-values ​​to track units in math functions, fixing the incorrect ordering of animation property.
Fix #1527
=> fix(postcss-ordered-values): incorrect order when using calc for animation property

.changeset/wild-scissors-grab.md, packages/postcss-discard-duplicates/src/index.js, packages/postcss-discard-duplicates/test/index.js
Closes https://github.com/cssnano/cssnano/issues/1655
I'm reasonably sure the @layer cannot be deduplicated as it may affect order. Let me know if I've misunderstood.
=> Fix layer rule deduping

site/src/styles/index.css
=> docs: make footer sticky

packages/cssnano/src/index.js
The default preset is a widely relied on, especially by frameworks (e.g. nuxt).
Currently, this means the hot path will have to `require` the preset and _block until resolution finishes_.
If we load the default preset up front, it means the call to cssnano doesn't need to do this and will actually run faster.
This does mean initial load is likely technically slower, but the gain of the call performance seems to outweigh this.
of course this is a balance. if you don't want the cost of resolving one more module (for all users), feel free to close this. though i suspect most consumers are loading the default already
=> perf: load default preset in startup

packages/cssnano-preset-default/src/index.js, packages/postcss-minify-selectors/src/index.js, packages/postcss-minify-selectors/test/index.js, packages/postcss-minify-selectors/types/index.d.ts
feat(minify-selectors): Add the ability to disable sorting when minifying selectors
=> Add support for selector order preservation to postcss-minify-selectors

CONTRIBUTORS.md, packages/postcss-convert-values/src/index.js, packages/postcss-convert-values/test/index.js, packages/postcss-minify-selectors/test/index.js
Fixes https://github.com/cssnano/cssnano/issues/1694
The `shouldKeepZeroUnit` check previously expected the syntax value `<percentage>` to be enclosed only in single quotes. However, in CSS, string values can also be surrounded by double quotes. I've added an additional check to handle both quote styles and updated the test cases to include the double-quoted variant.
NOTE: I didn't change any logic in `packages/postcss-minify-selectors/test/index.js`, but the file was automatically updated after running the `pnpm fixlint` command.
=> fix(postcss-convert-values): preserve percent sign in percentage values in at-rules with double quotes 

.github/workflows/publish.yml, .github/workflows/test.yml, .npmrc, package.json, pnpm-workspace.yaml
To ease management and avoid conflicts with npm, pnpm supports moving all configurations to the pnpm-workspace.yaml file. For more [github.com/orgs/pnpm/discussions/9037](https://github.com/orgs/pnpm/discussions/9037)
Add the `packageManager` field to facilitate users to automatically switch to the specified version of pnpm when installing dependencies locally to prevent unnecessary conflicts.
=> chore: add `packageManager` field & move pnpm setting

packages/postcss-convert-values/src/index.js, packages/postcss-convert-values/test/index.js
fix https://github.com/cssnano/cssnano/issues/1719
This fixes a problem where the `%` was stripped from 0 values in the `linear()` function.
I also added a test for it.
=> fix(convert-values): exclude `linear()` from stripping `%` from value 0
